# Site settings
title:            "Gabin Aureche, Front End Developer"
author:           "Gabin Aureche"
email:            "hello@gabinaureche.com"
twitter_username: "@zh0uzi"
facebook_url:     "http://facebook.com/gabin.aureche"
baseurl:          ""
url:              "http://gabinaureche.com"

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.



# Build settings
markdown:   kramdown
permalink:  pretty
exclude:    [ "gulpfile.js", "node_modules", "package.json" ]