# Site settings
title:            "Gabin Aureche, Front End Developer"
author:           "Gabin Aureche"
email:            "hello@gabinaureche.com"
twitter_username: "@zh0uzi"
facebook_url:     "http://facebook.com/gabin.aureche"
baseurl:          ""
url:              "http://gabinaureche.com"
description:      "Bonjour! I'm Gabin Aureche, a front-end developer focused on user experience."



# Build settings
markdown:   kramdown
permalink:  pretty
exclude:    [ "gulpfile.js", "node_modules", "package.json" ]



# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "thought"
      comments: true