# Site settings
title: Gabin Aureche, UX Front-End Developer
email: hello@gabinaureche.com
description: "Gabin Aureche is a User Experience Front-End Developer."
baseurl: ""
url: "http://gabinaureche.com"
twitter_username: zh0uzi
github_username:  zhouzi

# Build settings
markdown: kramdown
permalink: pretty
exclude: [ "css/scss", "scripts/partials" ]